name: Pull Request checks

on:
    push:
        branches: [master]

jobs:
    build:
        name: Build app
        runs-on: ubuntu-latest
        steps:
            - name: 🛑 Cancel Previous Runs
              uses: styfle/cancel-workflow-action@0.9.1

            - name: Check out repo
              uses: actions/checkout@v2

            - name: Install deps
              uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.0.2
                  run_install: true

            - name: Build
              run: pnpm build
